on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

name: CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1

      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v1
        with: { mdbook-version: 'latest' }

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - uses: actions-rs/install@v0.1
        with:
          crate: mdbook-graphviz
          version: latest
          use-tool-cache: true

      - run: mdbook build
      - run: mdbook test
