on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

name: CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v1
        with: { mdbook-version: 'latest' }

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: mdbook-graphviz Cache
        id: mdbook_graphviz_cache
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/mdbook-graphviz
          key: ${{ runner.os }}-mdbook-graphviz

      - # FIXME: Switch back when actions-rs/cargo#217 gets merged
        uses: r3-os/actions-rust-cargo@fb222fe18dc90e381546d012f9e3d6f353f0f627
        if: steps.mdbook_graphviz_cache.outputs.cache-hit != 'true'
        with:
          command: install
          args: mdbook-graphviz

      - run: mdbook build
      - run: mdbook test
